import Head from "next/head";
import { useState, useEffect } from "react";
import { addDoc, collection, query, onSnapshot } from "firebase/firestore";
import { db, auth } from "../lib/firebase";
import TaskItem from "./TaskItem";
import { onAuthStateChanged } from "firebase/auth";

export default function Home(props) {
	const [input, setInput] = useState("");
	const [tasks, setTasks] = useState([{ id: "", title: "" }]);

	const newTodo = async (e) => {
		await addDoc(collection(db, "tasks"), { title: input });
		setInput("");
	};

	useEffect(() => {
		const q = query(collection(db, "tasks"));
		const unSub = onSnapshot(q, (querySnapshot) => {
			setTasks(
				querySnapshot.docs.map((doc) => ({
					id: doc.id,
					title: doc.data().title,
				}))
			);
		});
		return () => unSub();
	}, []);

	// useEffect(() => {
	// 	const unsub = onAuthStateChanged(auth, (user) => {
	// 		!user && props.history.push("login");
	// 	});
	// 	return () => unsub();
	// });

	return (
		<div className={`w-2/5 mx-auto flex flex-col items-center mt-16`}>
			<Head>
				<title>Next Todo App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={`flex`}>
				<input
					placeholder="input new Todo"
					value={input}
					onChange={(e) => setInput(e.target.value)}
					className={`border-2 border-indigo-500 pl-2`}
				/>
				<button
					onClick={newTodo}
					className={`ml-1 bg-indigo-500 text-white py-1 px-2`}>
					Add
				</button>
			</div>
			<div className={`mt-8`}>
				{tasks.map((task) => (
					<TaskItem key={task.id} id={task.id} title={task.title} />
				))}
			</div>
		</div>
	);
}
